### ISSUE TITLE
Release on npm

### ISSUE THREAD

**Issue by sindrenm** [brianchirls/proto-loader#3]
This package doesn't seem to be available on npm, or at least I cannot find it under the name _[proto-loader](https://www.npmjs.com/package/proto-loader)_.

**Comment by brianchirls** [comment]
Hey, thanks for filing these. For some reason, I didn't get a notification that anyone had file issues or pull requests. I'll take a look this week.

**Comment by vjpr** [comment]
+1

**Comment by brianchirls** [comment]
Package name is fixed.

Would you guys mind sharing your opinions on #4? That would break any existing code, so I'd like to get that resolved before releasing on npm. Thanks.

**Comment by watsoncj** [comment]
I'm all for the usage simplification. What do you think of publishing the current version to npm?

Any breaking changes should be published [under a new major version](http://semver.org/).

**Comment by sindrenm** [comment]
Considering project hasn't reached 1.0.0 yet, I wouldn't be too concerned about publishing a new major version, since it's per the spec still in a pre-release stage. I would instead keep increasing the minor version until you feel it's stable and ready for release.

**Comment by quasor** [comment]
@brianchirls Any chance you'll merge this and #4 soon?

**Comment by brianchirls** [comment]
Please see the comment in #4: I'm putting off that change indefinitely.

As for the npm release, how about now? Does [now](https://www.npmjs.com/package/proto-loader) work for you?

**Comment by sindrenm** [comment]
:+1:
